name: UI tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download previous history
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: history

      - name: Run tests in Docker
        run: |
          docker build -t autotests .
          docker run --rm -v ${{ github.workspace }}:/app autotests

      - name: Copy history into report
        run: |
          mkdir -p allure-report/history
          cp -r history/* allure-report/history/ || true

      - name: Upload new history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report