name: Run AQA Tests Manually

on:
  workflow_dispatch:  # запускается вручную через GitHub UI

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-tests .

      - name: Run tests in Docker
        run: |
          docker run --name test-container my-tests || true
          docker cp test-container:/app/allure-report ./allure-report
          docker cp test-container:/app/allure-results ./allure-results
          docker rm test-container

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results